language: "perl"
perl:
  - "5.26"
install:
  - "cpanm --installdeps ."
jobs:
  include:
    - stage: syntax
      name: "Perl syntax"
      script: "perl -cT photodb"
    - name: "PerlCritic"
      script: "perlcritic --stern ."
    - stage: docs
      name: "Usage documentation"
      script: "perl -w check-usage-docs.pl"
    - name: "Function documentation"
      script: "perl -w check-func-docs.pl"
