language: "perl"
perl:
  - "5.26"
env:
  - "PERL5LIB=$TRAVIS_BUILD_DIR/lib"
install:
  - "cpanm --installdeps ."
jobs:
  include:
    - stage: tests
      name: "Perl syntax"
      script: "perl -cw bin/photodb"
    - name: "PerlCritic"
      script: "perlcritic --stern lib bin"
    - name: "Perl tests"
      script: "perl Build.PL && ./Build test"
    - stage: docs
      name: "Usage documentation"
      script: "perl -w ci/check-usage-docs.pl"
    - name: "Function documentation"
      script: "perl -w ci/check-func-docs.pl"
