language: "perl"
perl:
  - "5.26"
install:
        - "cpanm --installdeps ."
script:
        - "perl -cT photodb"
        - "perl -w check-usage-docs.pl"
        - "perl -w check-func-docs.pl"
        - "perlcritic --stern ."
