language: "perl"
perl:
  - "5.26"
env:
  - "PERL5LIB=$TRAVIS_BUILD_DIR/lib"
install:
  - "cpanm --installdeps ."
jobs:
  include:
    - stage: tests
      name: "Perl syntax"
      script: "perl -cw script/photodb"
    - name: "PerlCritic"
      script: "perlcritic --stern lib script"
    - name: "Perl tests"
      script: "make test"
    - stage: docs
      name: "Usage documentation"
      script: "perl -w check-usage-docs.pl"
    - name: "Function documentation"
      script: "perl -w check-func-docs.pl"
