language: perl
perl:
- '5.26'
env:
  global:
  - PERL5LIB=$TRAVIS_BUILD_DIR/lib
  - secure: ERaAHRIEwrs9nuQGomdFizcsMwlh150KGD6nd45NZ+qvIKDFnOHuIOAwtsX4ptCfUIWjJl4qTIpAEno3x2sONZgrUMsudEIiVfngc2nycf5+mvZDbfcJUJXG4cXtSkQA63jtpuq9G/TOTtJ1vZdtL+9def6VsuV9Bbm3udPe8iI=
jobs:
  include:
  - stage: test
    script: perl Build.PL && ./Build && ./Build dist
  - stage: migrations
    script: tests/migrations.sh
deploy:
- provider: releases
  api_key:
    secure: D16t4VJ9pHLDbdEu6XQ0kVAEWYbjgIRrz6y6S4n72nCU2LBkhdbATyjb/VAVFLesskQVr9aS90b7vJHR+2Jl+ID0D9CpG3pJnBIB+ZB/ECMDN3EVzuqZxHl/pX+FRNPrpH548TShnK0TiRPCOdIr6NCeugBBKchCtSRuXG4Omgs=
  file: App-PhotoDB-${TRAVIS_TAG}.tar.gz
  on:
    tags: true
  skip_cleanup: true
  overwrite: true
- provider: script
  script: sudo apt-get install -y libcpan-uploader-perl && cpan-upload --dry-run -u JGAZELEY -p ${PAUSE_PASS} App-PhotoDB-${TRAVIS_TAG}.tar.gz
  on:
    tags: true
